services:
  rust_devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ../:/workspace
    working_dir: /workspace
    environment:
      TZ: Asia/Tokyo
  db:
    image: postgres:13
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
